package ion.parser;

public enum ASTType {

    PRINT,
    BLOCK,
    STATEMENT_IF, STATEMENT_WHILE,
    STRING, INTEGER, FLOAT, BOOLEAN,
    ASSIGNMENT,
    COMPARISON,
    VARIABLE, VARIABLE_DECLARATION,
    DECREMENT, INCREMENT;

}
