package ion.lexer;

public enum TokenType {

    IDENTIFIER,
    INTEGER, FLOAT, STRING, BOOLEAN,
    PLUS, MINUS, MULTIPLY, DIVIDE,
    LT, GT, EQ, LTEQ, GTEQ, NEQ, NOT,
    ASSIGN, RIGHT_ARROW_SINGLE, RIGHT_ARROW_DOUBLE,
    OPERATOR, DECREMENT, INCREMENT,
    SEMICOLON, COLON, DOT, COMMA, LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK,
    KEYWORD,
    EOF;

}
